On utilise depuis peu le bloc de colonnes B_... de la table borrowers pour gérer les contentieux.
Ce bloc n'est plus accessible depuis assez longtemps.

Questions :
- on sait que ce bloc contient des informations autres que celles relatives aux contentieux => les identifier, pour éventuellement les supprimer ou les récuperer dans un autre bloc
- une fois que l'adhérent n'est plus en contentieux, les infos relatives au contentieux doivent être supprimées. Cela n'a jamais été fait, mettre au point une méthode d'analyse pour identifier les cartes concernées.

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime
from datetime import date

from kiblib.utils.db import DbConn

import requests
import json

In [2]:
def mod_borrower(userid, data):
    api_url = "http://cataloguekoha.ntrbx.local/cgi-bin/koha/rest.pl/user"
    url = f"{api_url}/{userid}"
    data = json.dumps(data)
    data2mod = f"data={data}"
    print(data2mod)
    response = requests.put(url, data=data2mod)
    print(f"{userid} : {response.content}")

In [3]:
db_conn = DbConn().create_engine()

# Préparation des données
- on part de la table borrowers pour créer un dataframe "adherents"
- création du dataframe "adh_bloc_ctx" : on ne garde du dataframe "adherents" que les colonnes permettant de bien caractériser l'adhérent (âge, type carte, site, date inscription, date expiration) et les colonnes du bloc B_...
- on ajoute à "adh_bloc_ctx" une colonne "contentieux", avec une valeur vrai/faux, via une jointure sur un dataframe reprenant les adhérents en contentieux.

In [28]:
#query = """SELECT * 
#FROM koha_prod.borrowers b"""
#adherents = pd.read_sql(query, db_conn)

adherents = pd.read_json("http://cataloguekoha.ntrbx.local/cgi-bin/koha/rest.pl/user")
len(adherents)

31777

In [29]:
adh_bloc_ctx = adherents[['borrowernumber', 'cardnumber', 'userid', 'B_address', 'B_address2', 'B_city', 'B_state',
       'B_zipcode', 'B_country', 'contactnote', 'dateofbirth',
       'branchcode', 'categorycode', 'dateenrolled', 'dateexpiry']]
# on exclut les cartes de collectivités
adh_bloc_ctx = adh_bloc_ctx[adh_bloc_ctx['categorycode'].isin(["CSVT", "CSLT", "BIBL", "MEDB", "MEDA", "MEDC", "MEDP", "COLD", "COLI"])]

In [30]:
# on crée un dataframe avec les adhérents en contentieux
query = """SELECT borrowernumber, DATE(date_due) as date_due
FROM koha_prod.issues i
WHERE date_due + INTERVAL 28 DAY <= CURDATE()
ORDER BY borrowernumber, date_due DESC"""
contentieux = pd.read_sql(query, db_conn)
contentieux['contentieux'] = True
contentieux = contentieux.drop_duplicates(subset='borrowernumber')

adh_bloc_ctx = adh_bloc_ctx.merge(contentieux, how='left', on='borrowernumber')
adh_bloc_ctx.loc[adh_bloc_ctx['contentieux'].isna(), 'contentieux'] = False

adh_bloc_ctx['contentieux'].value_counts()

False    28641
True      2546
Name: contentieux, dtype: int64

In [31]:
contentieux

       borrowernumber    date_due  contentieux
0                  72  2019-11-12         True
1                 237  2018-02-24         True
2                 344  2018-02-24         True
3                 478  2018-02-24         True
4                 891  2019-02-09         True
...               ...         ...          ...
10267           86144  2025-07-23         True
10268           86243  2025-07-17         True
10269           86318  2025-07-16         True
10277           86366  2025-07-18         True
10278           86382  2025-07-20         True

[2746 rows x 3 columns]

In [32]:
# pour chaque champs, on a parfois des valeurs vides : on les passe en np.nan pour faciliter les requêtes
for c in adh_bloc_ctx.columns:
    adh_bloc_ctx.loc[adh_bloc_ctx[c] == '', c] = np.nan

# Gestion : correction des données
On supprime les infos du bloc contentieux pour les personnes qui ne sont pas en contentieux.

In [33]:
# pour plus de facilité, on peut renommer les champs dédiés à la gestion des contentieux
adh_bloc_ctx_lib = adh_bloc_ctx.rename(columns={"B_address":"date_appel_telephonique",
                              "B_address2":"resultat_appel",
                              "B_city":"date_demande_creation_tiers",
                              "B_state":"numero_titre_recette",
                              "B_zipcode":"numero_tiers_GF",
                              "B_country":"date_creation_titre_recette",
                              "contactnote":"documents_a_payer"})

On ne garde que les lignes pour lesquelles le bloc comprend des données.

In [34]:
adh_bloc_ctx_lib_with_data = adh_bloc_ctx_lib[(~adh_bloc_ctx_lib['date_appel_telephonique'].isna())
                                    | (~adh_bloc_ctx_lib['resultat_appel'].isna())
                                    | (~adh_bloc_ctx_lib['date_demande_creation_tiers'].isna())
                                    | (~adh_bloc_ctx_lib['numero_titre_recette'].isna())
                                    | (~adh_bloc_ctx_lib['numero_tiers_GF'].isna())
                                    | (~adh_bloc_ctx_lib['date_creation_titre_recette'].isna())
                                    | (~adh_bloc_ctx_lib['documents_a_payer'].isna())]
len(adh_bloc_ctx_lib_with_data)

2510

pour chaque colonne contentieux, les valeurs admises sont les suivantes :
- date_appel_telephonique : date au format AAAA-MM-JJ
- resultat_appel : ['usager joint', 'message vocal', 'téléphone inconnu']
- date_demande_creation_tiers : date au format AAAA-MM-JJ
- numero_titre_recette : numéro
- numero_tiers_GF : nombre
- date_creation_titre_recette : date au format AAAA-MM-JJ
- documents_a_payer : texte

In [35]:
# on identifie les lignes qui posent pb
# 
adh_bloc_ctx_lib_with_data_pb = adh_bloc_ctx_lib_with_data[
    ( 
        (~adh_bloc_ctx_lib_with_data['date_appel_telephonique'].astype(str).str.match("\d{4}-\d{2}-\d{2}"))
      & (adh_bloc_ctx_lib_with_data['date_appel_telephonique'].notna()) 
    )
    
      | (  
        (~adh_bloc_ctx_lib_with_data['resultat_appel'].isin(['usager joint', 'message vocal', 'téléphone inconnu']))
      & (adh_bloc_ctx_lib_with_data['resultat_appel'].notna()) 
    )
    
  | (  
        (~adh_bloc_ctx_lib_with_data['numero_titre_recette'].astype(str).str.match("\d"))
      & (adh_bloc_ctx_lib_with_data['numero_titre_recette'].notna()) 
    )
    
  | (  
        (~adh_bloc_ctx_lib_with_data['numero_tiers_GF'].astype(str).str.match("\d"))
      & (adh_bloc_ctx_lib_with_data['numero_tiers_GF'].notna()) 
    )  
    
  | (  
        (~adh_bloc_ctx_lib_with_data['date_demande_creation_tiers'].astype(str).str.match("\d{4}-\d{2}-\d{2}"))
      & (adh_bloc_ctx_lib_with_data['date_demande_creation_tiers'].notna()) 
    )
    
  | (  
        (~adh_bloc_ctx_lib_with_data['date_creation_titre_recette'].astype(str).str.match("\d{4}-\d{2}-\d{2}"))
      & (adh_bloc_ctx_lib_with_data['date_creation_titre_recette'].notna()) 
    )
]
len(adh_bloc_ctx_lib_with_data_pb)

0

On isole les lignes pour lesquelles il n'y a pas de contentieux.

In [36]:
adh_bloc_ctx_lib_with_data_without_ctx = adh_bloc_ctx_lib_with_data[adh_bloc_ctx_lib_with_data['contentieux'] == False]
len(adh_bloc_ctx_lib_with_data_without_ctx)

160

In [15]:
adh_bloc_ctx_lib_with_data_without_ctx[~adh_bloc_ctx_lib_with_data_without_ctx['date_appel_telephonique'].isna()]

,borrowernumber,cardnumber,userid,date_appel_telephonique,resultat_appel,date_demande_creation_tiers,numero_titre_recette,numero_tiers_GF,date_creation_titre_recette,documents_a_payer,dateofbirth,branchcode,categorycode,dateenrolled,dateexpiry,date_due,contentieux
1,28.0,X0001659292,X0001659292,2024-03-07,message vocal,NaN,NaN,NaN,NaN,NaN,2007-12-21,MED,BIBL,2012-02-08,2024-07-22,NaN,False
13,181.0,X0002540139,X0002540139,2024-08-27,usager joint,NaN,NaN,NaN,NaN,NaN,2006-08-25,MED,BIBL,2014-04-29,2025-03-14,NaN,False
19,248.0,X0002288192,X0002288192,2025-07-31,message vocal,NaN,NaN,NaN,NaN,NaN,1986-11-29,MED,BIBL,2010-10-07,2025-06-29,NaN,False
22,297.0,X0001961898,X0001961898,2023-09-19,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,1974-12-17,MED,BIBL,2005-03-31,2025-11-21,NaN,False
23,299.0,X0002751115,X0002751115,2024-01-26,message vocal,NaN,NaN,NaN,NaN,NaN,2010-08-22,MED,BIBL,2012-07-07,2024-09-01,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30767,86563.0,X0002831442,X0002831442,2022-07-05,message vocal,2022-08-26,0,0,2022-08-26,C2100000684 - 5.95,2021-12-23,MED,BIBL,2025-07-23,2026-07-23,NaN,False
30788,86584.0,X0002831916,X0002831916,2025-04-01,message vocal,NaN,NaN,NaN,NaN,NaN,2016-10-27,MED,BIBL,2025-07-23,2026-07-23,NaN,False
30835,86632.0,X0002831336,X0002831336,2024-08-28,message vocal,NaN,NaN,NaN,NaN,NaN,1983-07-27,MED,CSVT,2025-07-26,2026-07-26,NaN,False
30895,86696.0,X0002832654,X0002832654,2024-08-27,usager joint,NaN,NaN,NaN,NaN,NaN,2025-02-23,MED,BIBL,2025-08-02,2026-08-02,NaN,False
31009,86810.0,X0002834955,X0002834955,2024-04-10,usager joint,NaN,NaN,NaN,NaN,NaN,2022-06-13,MED,BIBL,2025-08-16,2026-08-16,NaN,False

In [16]:
ctx2clean = adh_bloc_ctx_lib_with_data_without_ctx[~adh_bloc_ctx_lib_with_data_without_ctx['date_appel_telephonique'].isna()]
userid2clean = ctx2clean['userid'].tolist()

In [26]:
data = {"B_address": None,
        "B_address2": None}
#        "B_city": None,
#        "B_state": None,
#        "B_zipcode": None,
#        "B_country": None,
#        "contactnote": None}
for userid in userid2clean[:500]:
    mod_borrower(userid, data)

data={"B_address": null, "B_address2": null}
X0002684260 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
x0002835976 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002684635 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002768557 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002836027 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002836034 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002836041 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002835709 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
x0002835723 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002682112 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002681863 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002681825 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002681757 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002681207 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
x0002836157 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002681214 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002680927 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002681498 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002776408 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002680422 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002805306 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002805269 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0001948783 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002804415 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002805061 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002804385 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002804071 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002803982 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002804101 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002804651 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002682334 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002803616 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002612843 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002803234 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002802510 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002802442 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002802961 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002801384 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002801216 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002801643 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002801636 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002801841 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002800417 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002809526 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002809489 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002799766 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002810157 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002800905 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002800806 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002808161 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002808086 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002807812 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002769127 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002807690 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
x0002806624 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002806778 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002769097 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002806617 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002806365 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002777610 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002806334 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
x0002806273 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002805719 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002805641 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002806099 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002805429 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002805436 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002805504 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002844602 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002844596 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}

X0002844237 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002844299 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002843520 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002776088 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002844312 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002844053 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002844909 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002612935 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002612942 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002843179 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002843193 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002842882 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002842035 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002840727 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002840925 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002840918 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002840482 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002825311 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002825212 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002824475 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002841403 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002823836 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002823775 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002824253 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002824369 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
2208 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002841212 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002824420 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002823195 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002822716 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002822426 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002843872 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002821733 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002821788 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002821290 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002821306 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002821139 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002821504 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002820736 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002820934 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002799759 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002820484 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002800226 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002799667 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002799049 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002798561 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002798509 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002798493 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002798097 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002798028 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002797984 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002798295 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002797465 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002798202 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002798196 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002798165 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002797359 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002797113 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002796284 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002796239 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002796130 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002795812 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002795737 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002799438 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002796765 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002784854 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002789682 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002789835 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002788999 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002789545 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}

X0002788784 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002788531 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002788111 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002788098 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002787695 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002789163 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002789293 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002787633 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002787060 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002786506 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002786483 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002790206 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002790190 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002787527 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002785523 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002785493 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002785653 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002795256 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002795096 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002819662 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002794778 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002793528 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002794303 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002794242 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002792378 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002793511 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002792729 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002792699 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002786711 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002793986 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002793382 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002786568 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002793399 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002791142 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002790862 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002790800 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002819884 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002819686 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002301051 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002818580 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002818412 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002792019 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002472973 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002817347 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002817392 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002816791 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002816784 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002816920 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002791593 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002816081 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002815558 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002815190 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002779478 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002813851 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002814483 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002814360 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002813547 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002812724 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002812694 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002812496 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002812359 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002811727 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002811383 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002815923 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002810645 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002810638 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
x0002793627 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002810447 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002555249 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002811215 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002811208 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002811192 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002775579 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}

X0002776125 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002775746 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002776965 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002776538 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002777658 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002777313 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002778143 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002778389 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002791890 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002778983 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002779188 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002854472 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002853420 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002471754 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002854687 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002852355 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002851846 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002831442 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002831916 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002831336 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null}
X0002832654 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null}
X0002834955 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'

On isole les lignes pour lesquelles il y a contentieux.

In [27]:
adh_bloc_ctx_lib_with_data_with_ctx = adh_bloc_ctx_lib_with_data[adh_bloc_ctx_lib_with_data['contentieux'] == True]
len(adh_bloc_ctx_lib_with_data_with_ctx)

2350

In [37]:
adh_bloc_ctx_lib_with_data_with_ctx['date_due_'] = pd.to_datetime(adh_bloc_ctx_lib_with_data_with_ctx['date_due'])
adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique_'] = pd.to_datetime(adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique'])

In [43]:
adh_bloc_ctx_lib_with_data_with_ctx.loc[
    adh_bloc_ctx_lib_with_data_with_ctx['date_due_'] > adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique_'],
    'ctx_statut'
] = 'nouveau'
adh_bloc_ctx_lib_with_data_with_ctx['newctx_appel'] = (adh_bloc_ctx_lib_with_data_with_ctx['date_due_'] - adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique_']).dt.days

In [39]:
adh_bloc_ctx_lib_with_data_with_ctx['ctx_statut'].value_counts()

nouveau    351
Name: ctx_statut, dtype: int64

In [45]:
new_ctx = adh_bloc_ctx_lib_with_data_with_ctx[adh_bloc_ctx_lib_with_data_with_ctx['ctx_statut'] == 'nouveau']
new_ctx

,borrowernumber,cardnumber,userid,date_appel_telephonique,resultat_appel,date_demande_creation_tiers,numero_titre_recette,numero_tiers_GF,date_creation_titre_recette,documents_a_payer,...,branchcode,categorycode,dateenrolled,dateexpiry,date_due,contentieux,date_due_,date_appel_telephonique_,ctx_statut,newctx_appel
176,2030.0,X0002587394,X0002587394,2021-10-22,usager joint,2025-08-19,NaN,201254,NaN,C1400006532 - 9.90\r\nC1400009101 - 22.00,...,MED,BIBL,2022-10-25,2025-01-05,2024-02-16,True,2024-02-16,2021-10-22,nouveau,847.0
213,2418.0,X0002349756,X0002349756,2023-07-15,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,...,MED,MEDC,2007-02-28,2026-05-06,2025-07-15,True,2025-07-15,2023-07-15,nouveau,731.0
227,2577.0,X0002039459,X0002039459,2023-09-19,message vocal,NaN,NaN,NaN,NaN,NaN,...,BUS,BIBL,2008-08-28,2026-02-05,2025-05-31,True,2025-05-31,2023-09-19,nouveau,620.0
268,2973.0,X0002716022,X0002716022,2022-11-05,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2010-07-24,2025-02-21,2024-05-16,True,2024-05-16,2022-11-05,nouveau,558.0
271,3020.0,X0002550497,X0002550497,2024-09-19,message vocal,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2006-08-09,2026-01-19,2025-07-12,True,2025-07-12,2024-09-19,nouveau,296.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29080,84858.0,X0002818702,X0002818702,2025-06-13,usager joint,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-03-23,2026-03-23,2025-07-09,True,2025-07-09,2025-06-13,nouveau,26.0
29404,85183.0,X0002814919,X0002814919,2023-02-03,message vocal,2023-09-20,20230138,100168,2023-09-21,C2400002345 - 33.00,...,MED,BIBL,2025-04-11,2026-04-11,2025-06-10,True,2025-06-10,2023-02-03,nouveau,858.0
29430,85209.0,X0002814520,X0002814520,2025-02-06,message vocal,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-04-15,2026-04-15,2025-05-06,True,2025-05-06,2025-02-06,nouveau,89.0
30525,86318.0,X0002851853,X0002851853,2021-05-15,message vocal,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-06-25,2026-06-25,2025-07-16,True,2025-07-16,2021-05-15,nouveau,1523.0
30588,86382.0,X0002851457,X0002851457,2021-05-19,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-06-29,2026-06-29,2025-07-20,True,2025-07-20,2021-05-19,nouveau,1523.0

In [47]:
new_ctx[new_ctx['newctx_appel'] < 90].to_excel("test_ctx.xlsx")