In [1]:
import pandas as pd
from datetime import datetime as dt
from datetime import date

from kiblib.utils.db import DbConn

In [3]:
db_conn = DbConn().create_engine()

In [49]:
query = """SELECT itemnumber, biblionumber, barcode, dateaccessioned, booksellerid, homebranch, price, replacementprice, replacementpricedate, datelastborrowed, datelastseen, stack, notforloan, damaged, damaged_on, itemlost, itemlost_on, withdrawn, withdrawn_on, itemcallnumber, holdingbranch, `timestamp`, location, onloan, ccode
FROM koha_prod.deleteditems;"""

deleteditems = pd.read_sql(query,db_conn)

query = """SELECT itemnumber, biblionumber, barcode, dateaccessioned, booksellerid, homebranch, price, replacementprice, replacementpricedate, datelastborrowed, datelastseen, stack, notforloan, damaged, damaged_on, itemlost, itemlost_on, withdrawn, withdrawn_on, itemcallnumber, holdingbranch, `timestamp`, location, onloan, ccode
FROM koha_prod.items;"""

items = pd.read_sql(query,db_conn)

allitems = pd.concat([items, deleteditems])
len(allitems)

290673

In [50]:
query = """SELECT biblionumber, itemtype FROM koha_prod.deletedbiblioitems;"""

deletedbiblioitems = pd.read_sql(query,db_conn)

query = """SELECT biblionumber, itemtype FROM koha_prod.biblioitems;"""

biblioitems = pd.read_sql(query,db_conn)

allbiblioitems = pd.concat([biblioitems, deletedbiblioitems])
len(biblioitems)

236064

In [51]:
query = """SELECT biblionumber, title FROM koha_prod.deletedbiblio;"""

deletedbiblio = pd.read_sql(query,db_conn)

query = """SELECT biblionumber, title FROM koha_prod.biblio;"""

biblio = pd.read_sql(query,db_conn)

allbiblio = pd.concat([biblio, deletedbiblio])
len(biblio)

236064

In [52]:
allitems = allitems.merge(biblioitems, on='biblionumber', how='left')
allitems = allitems.merge(biblio, on='biblionumber', how='left')

In [53]:
query = """SELECT  * FROM statdb.stat_eliminations;"""

old = pd.read_sql(query,db_conn)
len(old)

213351

In [54]:
sortis = ['C0003918333', 'C0005649532', 'C0003172296', 'C0005453443', 'C2500000724', 'C2100001840', 'C0005423637', 'C0004332344', 'C2500000662', 'C0005300138', 'C0005283310', 'C0005027243', 'C0005751969', 'C0005775323', 'C0005442683', 'C0004458467', 'C0005768653', 'C0006005757', 'C0005052133', 'C0005575428', 'C0004347810', 'C3200012530', 'C2300008978']

In [55]:
pas_sortis = ['C2500013896', 'C0005314632', 'C1300000704', 'C0001748279', 'C1400000084', 'C2400003241', 'C2500025500', 'C2500016980', 'C2300010837', 'C0005953721', 'C0005524044', 'C0005345121', 'C2200006521', 'C3100000223', 'C2500000168', 'C1400017759', 'C1400005336', 'C0005327546', 'C0004493530', 'C1400002963', 'C1400006140', 'C3100008582', 'C3100008318', 'C0005128015', 'C2300008245', 'C2200004401', 'C0005800063', 'C2300008776', 'C1400009468', 'C1400008288', 'C2300009724', 'C2400001835', 'C0005143251', 'C0005560202', 'C0005956838', 'C0004333065', 'C2500012561', 'C2500016203', 'C1400013039', 'C1400009260', 'C3100011041', 'C0005648726', 'C2400002051', 'C2400002733', 'C3200012217', 'C2200006704', 'C3200008072', 'C3200017578', 'C3200036503', 'C3200014980', 'C3200016719', 'C2200006549', 'C3200020946', 'C3200021193', 'C3200021459', 'C3200010444', 'C3200025114', 'C3200014778', 'C3200017302']

In [56]:
ex_sort = pd.DataFrame({"barcode" : sortis})
ex_coll = pd.DataFrame({"barcode": pas_sortis})

In [57]:
ex_coll = ex_coll.merge(old, on='barcode', how='left')
ex_coll2 = ex_coll[ex_coll['biblionumber'].isna()]
ex_coll = ex_coll[~ex_coll['biblionumber'].isna()]
ex_coll2 = ex_coll2[['barcode']].merge(allitems, on='barcode', how='left')
ex_coll2

ex_coll_all = pd.concat([ex_coll, ex_coll2])
ex_coll_all

,barcode,itemnumber,biblionumber,biblioitemnumber,dateaccessioned,booksellerid,homebranch,price,replacementprice,replacementpricedate,...,itype,more_subfields_xml,enumchron,copynumber,stocknumber,annee_mise_pilon,itemtype,title,motif,damaged_on
0,C2500013896,396393.0,313119.0,313119.0,2019-07-06,None,MED,13.50,NaN,2019-07-06,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2023.0,LI,Crottes de bêtes !,perdu,NaT
2,C1300000704,329458.0,280609.0,280609.0,2015-10-23,None,MED,25.00,25.00,None,...,PRETLIV,None,None,None,None,2020.0,LI,Le grand imagier chinois,perdu,NaT
3,C0001748279,49431.0,42773.0,42773.0,2005-03-23,None,MED,29.88,29.88,None,...,PRETLIV,None,None,None,None,2019.0,LI,Suicides,perdu,NaT
4,C1400000084,351782.0,293228.0,293228.0,2016-11-25,None,MED,10.00,NaN,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2022.0,LI,Train d'enfer pour Ange rouge | suivi de Deuil...,abîmé,NaT
5,C2400003241,424616.0,332809.0,332809.0,2021-03-27,None,MED,25.00,NaN,2021-03-27,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,LI,Secrets d'histoire,désherbé,NaT
6,C2500025500,435900.0,341449.0,341449.0,2021-12-03,None,MED,16.90,NaN,2021-12-03,...,PRETLIV,None,None,None,None,2022.0,LI,File dans ta chambre !,perdu,NaT
7,C2500016980,406635.0,282179.0,282179.0,2020-02-20,None,MED,5.60,NaN,2020-02-20,...,PRETLIV,None,None,None,None,2021.0,LI,L'âne Trotro va à la cantine,abîmé,NaT
8,C2300010837,417119.0,331057.0,331057.0,2020-11-21,None,MED,22.95,NaN,2020-11-21,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,LI,Le judo pour les nuls,désherbé,NaT
9,C0005953721,308677.0,269158.0,269158.0,2014-08-23,60,MED,20.84,22.90,None,...,PRETLIV,None,None,None,None,2024.0,LI,Cancers du sein,perdu,NaT
10,C0005524044,287930.0,251510.0,251510.0,2012-11-06,None,MED,15.90,15.90,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2022.0,LI,Les basiques du boulanger,perdu,NaT
11,C0005345121,288876.0,252422.0,252422.0,2012-12-12,None,MED,10.70,10.70,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2020.0,LI,Les suspendues,perdu,NaT
12,C2200006521,366869.0,301680.0,301680.0,2017-10-17,None,MED,3.95,NaN,None,...,PRETLIV,None,None,None,None,2021.0,LI,Les 50 règles d'or zéro déchet,perdu,NaT
14,C2500000168,353780.0,294702.0,294702.0,2017-01-07,None,MED,45.00,NaN,None,...,PRETDVD,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2021.0,VD,Zootopie,perdu,NaT
16,C1400005336,389815.0,315304.0,315304.0,2019-02-20,None,MED,36.00,NaN,2019-02-20,...,PRETDVD,None,None,None,None,2024.0,VD,Climax,perdu,NaT
17,C0005327546,289750.0,253122.0,253122.0,2012-11-30,None,MED,29.71,29.71,None,...,PRETDVD,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2022.0,VD,La part des anges,perdu,NaT
19,C1400002963,372362.0,304970.0,304970.0,2018-02-07,None,MED,38.00,NaN,None,...,PRETDVD,None,None,None,None,2022.0,VD,L'impasse,perdu,NaT
20,C1400006140,394697.0,318117.0,318117.0,2019-06-07,None,MED,39.00,NaN,2019-06-07,...,PRETDVD,None,None,None,None,2021.0,VD,It Follows,perdu,NaT
21,C3100008582,413097.0,328556.0,328556.0,2020-08-20,None,MED,39.00,NaN,2020-08-20,...,PRETDVD,None,None,None,None,2022.0,VD,Habemus papam,perdu,NaT
22,C3100008318,411357.0,327638.0,327638.0,2020-07-17,None,MED,NaN,NaN,2020-07-17,...,PRETDVD,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,VD,Quelle folie,désherbé,NaT
23,C0005128015,261758.0,228258.0,228258.0,2010-12-09,None,MED,8.50,8.50,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2021.0,LI,Menus de fêtes,perdu,NaT
24,C2300008245,388061.0,314555.0,314555.0,2019-01-19,None,MED,6.95,NaN,2019-01-19,...,PRETLIV,None,None,None,None,2022.0,LI,Terrines et foies gras les + faciles du monde,perdu,NaT
25,C2200004401,349922.0,292118.0,292118.0,2016-10-18,None,MED,19.00,NaN,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2023.0,LI,Réinventer IKEA,désherbé,NaT
26,C0005800063,305548.0,266946.0,266946.0,2014-05-22,None,MED,9.95,9.95,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2022.0,LI,Cuisine créole,perdu,NaT
27,C2300008776,394606.0,317825.0,317825.0,2019-06-07,None,MED,12.95,NaN,2019-06-07,...,PRETLIV,None,None,None,None,2021.0,LI,Composter en ville,perdu,NaT
28,C1400009468,421951.0,334207.0,334207.0,2021-02-02,None,MED,16.90,NaN,2021-02-02,...,PRETLIV,None,None,None,None,2022.0,LI,Pourquoi les imbéciles ne changent pas d'avis,perdu,NaT
30,C2300009724,403276.0,322986.0,322986.0,2019-12-04,None,MED,24.95,24.95,2019-12-04,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2023.0,LI,"En 2 h, je cuisine veggie pour toute la semaine",perdu,NaT
31,C2400001835,387714.0,313798.0,313798.0,2019-01-11,None,MED,18.95,18.95,2019-01-11,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2023.0,LI,La science de l'illusion,désherbé,NaT
32,C0005143251,271847.0,237065.0,237065.0,2011-02-05,None,MED,6.90,6.90,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2023.0,LI,La mémoire fantôme,perdu,NaT
33,C0005560202,287559.0,251049.0,251049.0,2012-11-16,None,MED,8.10,8.10,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2022.0,LI,Wilderness,perdu,NaT
36,C2500012561,392022.0,316238.0,316238.0,2019-04-13,None,MED,4.90,NaN,2019-04-13,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,LI,Wild animals,perdu,NaT
37,C2500016203,404141.0,311863.0,311863.0,2019-12-21,None,BUS,14.50,14.50,2019-12-21,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,1,None,2023.0,LI,The amazing world of Gumball,abîmé,NaT
38,C1400013039,442033.0,345692.0,345692.0,2022-04-05,None,MED,7.99,NaN,2022-04-05,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,LI,Lasagnes,perdu,NaT
39,C1400009260,419961.0,333537.0,333537.0,2020-12-29,None,MED,19.90,NaN,2020-12-29,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,LI,Chez moi,désherbé,NaT
40,C3100011041,454173.0,352812.0,352812.0,2022-12-13,None,MED,13.47,NaN,2022-12-13,...,PRETLIV,None,None,None,None,2024.0,LI,L'art de moucher les fâcheux,désherbé,NaT
42,C2400002051,393517.0,316735.0,316735.0,2019-05-16,None,MED,24.90,24.90,2019-05-16,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,LI,L'histoire de France comme si vous y étiez !,désherbé,NaT
43,C2400002733,409291.0,326248.0,326248.0,2020-06-16,None,MED,NaN,NaN,2020-06-16,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2024.0,LI,Les plus belles histoires de l'escroquerie,désherbé,NaT
44,C3200012217,378126.0,308206.0,308206.0,2018-06-27,None,MED,15.90,NaN,2018-06-27,...,PRETLIV,None,None,None,None,2024.0,LI,Presque végétarien,perdu,NaT
45,C2200006704,369376.0,303063.0,303063.0,2017-12-08,None,MED,39.00,NaN,None,...,PRETLIV,None,None,None,None,2018.0,LI,On va déguster la France,perdu,NaT
49,C3200014980,389703.0,154629.0,154629.0,2019-02-15,None,MED,NaN,NaN,2019-02-15,...,PRETPER,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",N.457 - Mars 2019,None,None,2023.0,PE,Ca m'intéresse,désherbé,NaT
50,C3200016719,396067.0,229886.0,229886.0,2019-07-03,None,MED,NaN,NaN,2019-07-03,...,PRETPER,None,Tout comprendre max n°25 - Juillet 2019,None,None,2021.0,PE,Tout comprendre- Comment ça marche,désherbé,NaT
51,C2200006549,366896.0,157477.0,157477.0,2017-10-17,None,MED,NaN,NaN,None,...,PRETPER,None,N.241 - Octobre 2017,None,None,2022.0,PE,Saveurs,désherbé,NaT
52,C3200020946,410148.0,157477.0,157477.0,2020-06-30,None,MED,NaN,NaN,2020-06-30,...,PRETPER,None,N.265 - Juin 2020,None,None,2023.0,PE,Saveurs,désherbé,NaT
53,C3200021193,410562.0,157960.0,157960.0,2020-07-07,None,MED,NaN,NaN,2020-07-07,...,PRETPER,None,N.195 - Juillet 2020,None,None,2023.0,PE,Cuisine et vins de France,désherbé,NaT
57,C3200014778,388721.0,154653.0,154653.0,2019-01-30,None,MED,NaN,NaN,2019-01-30,...,PRETPER,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",N.866- Février 2019,None,None,2023.0,PE,Historia,désherbé,NaT
58,C3200017302,398020.0,157477.0,157477.0,2019-09-03,None,MED,NaN,NaN,2019-09-03,...,PRETPER,None,N.258 - Septembre 2019,None,None,2023.0,PE,Saveurs,désherbé,NaT
0,C0005314632,261078.0,227601.0,NaN,2010-11-17,None,MED,35.00,35.00,None,...,NaN,NaN,NaN,NaN,NaN,NaN,LI,D'art d'art !,NaN,NaT
1,C3100000223,329213.0,280526.0,NaN,2015-10-20,None,MED,15.78,21.61,None,...,NaN,NaN,NaN,NaN,NaN,NaN,DC,Compton,NaN,NaT
2,C1400017759,467595.0,359074.0,NaN,2023-10-19,None,MED,36.00,NaN,2023-10-19,...,NaN,NaN,NaN,NaN,NaN,NaN,VD,L'exorciste du Vatican,NaN,NaT
3,C0004493530,204497.0,180022.0,NaN,2007-01-06,None,MED,52.60,52.60,None,...,NaN,NaN,NaN,NaN,NaN,NaN,VD,Kagemusha,NaN,NaT
4,C1400008288,414938.0,329403.0,NaN,2020-09-30,None,MED,16.50,NaN,2020-09-30,...,NaN,NaN,NaN,NaN,NaN,NaN,LI,"Ensemble, on aboie en silence",NaN,2025-01-16 11:09:10
5,C0005956838,307816.0,268695.0,NaN,2014-07-25,None,MED,15.02,16.50,None,...,NaN,NaN,NaN,NaN,NaN,NaN,LI,Les religions du monde,NaN,NaT
6,C0004333065,203291.0,179065.0,NaN,2006-10-26,None,MED,18.00,18.00,None,...,NaN,NaN,NaN,NaN,NaN,NaN,LI,Les religions du monde,NaN,NaT
7,C0005648726,300405.0,262382.0,NaN,2013-12-21,None,MED,21.20,21.20,None,...,NaN,NaN,NaN,NaN,NaN,NaN,LI,Le grand livre de cuisine des enfants,NaN,NaT
8,C3200008072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
9,C3200017578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
10,C3200036503,473147.0,277577.0,NaN,2024-02-10,None,MED,NaN,NaN,2024-02-10,...,NaN,NaN,NaN,NaN,NaN,NaN,PE,Marmiton,NaN,NaT
11,C3200021459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
12,C3200010444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
13,C3200025114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [58]:
ex_coll_all['annee_mise_pilon'].value_counts()

2024.0    12
2023.0    11
2022.0    11
2021.0     7
2020.0     2
2019.0     1
2018.0     1
Name: annee_mise_pilon, dtype: int64

In [59]:
ex_coll_all['motif'].value_counts()

perdu       26
désherbé    16
abîmé        3
Name: motif, dtype: int64

In [60]:
ex_coll_all['price'].sum()

910.74

In [61]:
ex_sort = ex_sort.merge(old, on='barcode', how='left')
ex_sort2 = ex_sort[ex_sort['biblionumber'].isna()]
ex_sort = ex_sort[~ex_sort['biblionumber'].isna()]
ex_sort2 = ex_sort2[['barcode']].merge(allitems, on='barcode', how='left')
ex_sort2

ex_sort_all = pd.concat([ex_sort, ex_sort2])
ex_sort_all

,barcode,itemnumber,biblionumber,biblioitemnumber,dateaccessioned,booksellerid,homebranch,price,replacementprice,replacementpricedate,...,itype,more_subfields_xml,enumchron,copynumber,stocknumber,annee_mise_pilon,itemtype,title,motif,damaged_on
0,C0003918333,77488.0,68305.0,68305.0,2005-08-06,None,MED,11.50,11.50,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2015.0,LI,Le petit soldat qui cherchait la guerre,abîmé,NaT
1,C0005649532,296488.0,259069.0,259069.0,2013-12-20,None,MED,5.00,5.00,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2015.0,LI,Le petit livre des blagues et devinettes,désherbé,NaT
3,C0005453443,290300.0,253568.0,253568.0,2012-12-14,None,MED,22.50,22.50,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2017.0,LI,Nouveaux masques,désherbé,NaT
4,C2500000724,355054.0,275306.0,275306.0,2017-02-07,None,MED,10.60,NaN,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2020.0,LI,Poséidon d'avril,abîmé,NaT
5,C2100001840,331686.0,277580.0,277580.0,2015-11-27,None,MED,9.95,9.95,None,...,PRETLIV,None,None,None,None,2020.0,LI,The lapins crétins,abîmé,NaT
6,C0005423637,290965.0,254206.0,254206.0,2013-01-17,None,MED,34.90,34.90,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2016.0,LI,Les bonnes recettes des grands chefs du Nord e...,désherbé,NaT
7,C0004332344,205370.0,180498.0,180498.0,2006-12-12,None,MED,12.50,12.50,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2015.0,LI,Maudites lunettes,abîmé,NaT
8,C2500000662,354935.0,295246.0,295246.0,2017-02-02,None,MED,10.50,10.50,None,...,PRETLIV,None,None,None,None,2020.0,LI,Le cycle des magiciens,abîmé,NaT
9,C0005300138,157729.0,139113.0,139113.0,2009-10-28,None,MED,9.45,9.45,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2019.0,LI,Génie en ballade,abîmé,NaT
11,C0005027243,244989.0,214244.0,214244.0,2011-12-08,None,BUS,9.40,9.40,None,...,PRETLIV,None,None,None,None,2017.0,LI,Les aventures de Tintin,désherbé,NaT
12,C0005751969,312409.0,271419.0,271419.0,2014-12-06,None,MED,6.32,6.95,None,...,PRETLIV,None,None,None,None,2017.0,LI,Sport automobile,abîmé,NaT
13,C0005775323,316321.0,267065.0,267065.0,2015-01-02,None,BUS,10.60,10.60,None,...,PRETLIV,None,None,None,None,2017.0,LI,Bill de match,désherbé,NaT
14,C0005442683,272987.0,238161.0,238161.0,2011-10-28,None,MED,20.90,20.90,None,...,PRETLIV,"<?xml version=""1.0"" encoding=""UTF-8""?>\n<colle...",None,None,None,2019.0,LI,Vertige,abîmé,NaT
15,C0004458467,86557.0,76350.0,76350.0,2007-11-22,None,MED,9.45,9.45,None,...,PRETLIV,None,None,None,None,2020.0,LI,Gaston,abîmé,NaT
16,C0005768653,317787.0,274133.0,274133.0,2015-02-11,60,MED,21.38,23.49,None,...,PRETLIV,None,None,None,None,2021.0,LI,Mr Mercedes,non restitué,NaT
17,C0006005757,307630.0,215326.0,215326.0,2014-07-18,None,MED,NaN,NaN,2014-07-18,...,PRETPER,None,"Géo HS, été 2014, 6,90 euros",None,None,2015.0,PE,Spécimens de revues pour le prêt adultes,désherbé,NaT
18,C0005052133,174710.0,154824.0,154824.0,2010-07-09,None,MED,NaN,NaN,None,...,PRETPER,None,None,None,None,2015.0,PE,Géo,désherbé,NaT
19,C0005575428,246526.0,215326.0,215326.0,2012-07-13,None,MED,6.90,6.90,2014-06-30,...,PRETPER,None,Geo histoire N.3 de mai/juin 2012,None,None,2015.0,PE,Spécimens de revues pour le prêt adultes,désherbé,NaT
20,C0004347810,174690.0,154824.0,154824.0,2012-01-03,None,MED,NaN,NaN,None,...,PRETPER,None,N. 395 (Janvier 2012),395,None,2015.0,PE,Géo,désherbé,NaT
21,C3200012530,378968.0,215326.0,215326.0,2018-07-13,None,MED,NaN,NaN,2018-07-13,...,PRETPER,None,"Elle à table n°119 de juillet/août 2018, 3,90 ...",None,None,2021.0,PE,Spécimens de revues pour le prêt adultes,désherbé,NaT
22,C2300008978,395804.0,277577.0,277577.0,2019-06-27,None,MED,NaN,NaN,2019-06-27,...,PRETPER,None,N.48 - Juillet 2019,None,None,2022.0,PE,Marmiton,désherbé,NaT
0,C0003172296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,C0005283310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [62]:
ex_sort_all['annee_mise_pilon'].value_counts()

2015.0    7
2017.0    4
2020.0    4
2019.0    2
2021.0    2
2016.0    1
2022.0    1
Name: annee_mise_pilon, dtype: int64

In [63]:
ex_sort_all['motif'].value_counts()

désherbé        11
abîmé            9
non restitué     1
Name: motif, dtype: int64

In [64]:
ex_sort_all['price'].sum()

211.85

In [71]:
ex_coll_all = ex_coll_all[['barcode', 'itemnumber', 'biblionumber', 
       'dateaccessioned', 'homebranch', 'price',
       'datelastborrowed',
       'datelastseen', 'notforloan', 'damaged', 'itemlost',
       'itemlost_on', 'withdrawn', 'withdrawn_on', 'itemcallnumber',
       'timestamp',
       'location', 'onloan', 'ccode', 'annee_mise_pilon', 'itemtype', 'title',
       'motif', 'damaged_on']]
ex_coll_all.to_excel("20250712_pas_sortis_inventaire.xlsx", index=False)

In [72]:
ex_sort_all = ex_sort_all[['barcode', 'itemnumber', 'biblionumber', 
       'dateaccessioned', 'homebranch', 'price',
       'datelastborrowed',
       'datelastseen', 'notforloan', 'damaged', 'itemlost',
       'itemlost_on', 'withdrawn', 'withdrawn_on', 'itemcallnumber',
       'timestamp',
       'location', 'onloan', 'ccode', 'annee_mise_pilon', 'itemtype', 'title',
       'motif', 'damaged_on']]
ex_sort_all.to_excel("20250712_sortis_inventaire.xlsx", index=False)