On utilise depuis peu le bloc de colonnes B_... de la table borrowers pour gérer les contentieux.
Ce bloc n'est plus accessible depuis assez longtemps.

Questions :
- on sait que ce bloc contient des informations autres que celles relatives aux contentieux => les identifier, pour éventuellement les supprimer ou les récuperer dans un autre bloc
- une fois que l'adhérent n'est plus en contentieux, les infos relatives au contentieux doivent être supprimées. Cela n'a jamais été fait, mettre au point une méthode d'analyse pour identifier les cartes concernées.

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime
from datetime import date

from kiblib.utils.db import DbConn

import requests
import json

In [2]:
def mod_borrower(userid, data):
    api_url = "http://cataloguekoha.ntrbx.local/cgi-bin/koha/rest.pl/user"
    url = f"{api_url}/{userid}"
    data = json.dumps(data)
    data2mod = f"data={data}"
    print(data2mod)
    response = requests.put(url, data=data2mod)
    print(f"{userid} : {response.content}")

In [3]:
db_conn = DbConn().create_engine()

# Préparation des données
- on part de la table borrowers pour créer un dataframe "adherents"
- création du dataframe "adh_bloc_ctx" : on ne garde du dataframe "adherents" que les colonnes permettant de bien caractériser l'adhérent (âge, type carte, site, date inscription, date expiration) et les colonnes du bloc B_...
- on ajoute à "adh_bloc_ctx" une colonne "contentieux", avec une valeur vrai/faux, via une jointure sur un dataframe reprenant les adhérents en contentieux.

In [4]:
#query = """SELECT * 
#FROM koha_prod.borrowers b"""
#adherents = pd.read_sql(query, db_conn)

adherents = pd.read_json("http://cataloguekoha.ntrbx.local/cgi-bin/koha/rest.pl/user")
len(adherents)

33000

In [5]:
adh_bloc_ctx = adherents[['borrowernumber', 'cardnumber', 'userid', 'B_address', 'B_address2', 'B_city', 'B_state',
       'B_zipcode', 'B_country', 'contactnote', 'dateofbirth',
       'branchcode', 'categorycode', 'dateenrolled', 'dateexpiry']]
# on exclut les cartes de collectivités
adh_bloc_ctx = adh_bloc_ctx[adh_bloc_ctx['categorycode'].isin(["CSVT", "CSLT", "BIBL", "MEDB", "MEDA", "MEDC", "MEDP", "COLD", "COLI"])]

In [6]:
# on crée un dataframe avec les adhérents en contentieux
query = """SELECT borrowernumber, DATE(date_due) as date_due
FROM koha_prod.issues i
WHERE date_due + INTERVAL 28 DAY <= CURDATE()
ORDER BY borrowernumber, date_due DESC"""
contentieux = pd.read_sql(query, db_conn)
contentieux['contentieux'] = True
contentieux = contentieux.drop_duplicates(subset='borrowernumber')

adh_bloc_ctx = adh_bloc_ctx.merge(contentieux, how='left', on='borrowernumber')
adh_bloc_ctx.loc[adh_bloc_ctx['contentieux'].isna(), 'contentieux'] = False

adh_bloc_ctx['contentieux'].value_counts()

False    29900
True      2497
Name: contentieux, dtype: int64

In [25]:
ctx2 = adh_bloc_ctx[adh_bloc_ctx['contentieux'] == True]
ctx2['year'] = ctx2['date_due'].astype(str).str[0:4]
ctx2['year'].value_counts().reset_index().sort_values(by='index')

/tmp/ipykernel_21454/1697610370.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ctx2['year'] = ctx2['date_due'].astype(str).str[0:4]

  index  year
2  2018   345
3  2019   317
6  2020   255
7  2021   166
5  2022   271
4  2023   314
1  2024   371
0  2025   458

In [8]:
# pour chaque champs, on a parfois des valeurs vides : on les passe en np.nan pour faciliter les requêtes
for c in adh_bloc_ctx.columns:
    adh_bloc_ctx.loc[adh_bloc_ctx[c] == '', c] = np.nan

# Gestion : correction des données
On supprime les infos du bloc contentieux pour les personnes qui ne sont pas en contentieux.

In [9]:
# pour plus de facilité, on peut renommer les champs dédiés à la gestion des contentieux
adh_bloc_ctx_lib = adh_bloc_ctx.rename(columns={"B_address":"date_appel_telephonique",
                              "B_address2":"resultat_appel",
                              "B_city":"date_demande_creation_tiers",
                              "B_state":"numero_titre_recette",
                              "B_zipcode":"numero_tiers_GF",
                              "B_country":"date_creation_titre_recette",
                              "contactnote":"documents_a_payer"})

On ne garde que les lignes pour lesquelles le bloc comprend des données.

In [10]:
adh_bloc_ctx_lib_with_data = adh_bloc_ctx_lib[(~adh_bloc_ctx_lib['date_appel_telephonique'].isna())
                                    | (~adh_bloc_ctx_lib['resultat_appel'].isna())
                                    | (~adh_bloc_ctx_lib['date_demande_creation_tiers'].isna())
                                    | (~adh_bloc_ctx_lib['numero_titre_recette'].isna())
                                    | (~adh_bloc_ctx_lib['numero_tiers_GF'].isna())
                                    | (~adh_bloc_ctx_lib['date_creation_titre_recette'].isna())
                                    | (~adh_bloc_ctx_lib['documents_a_payer'].isna())]
len(adh_bloc_ctx_lib_with_data)

2827

pour chaque colonne contentieux, les valeurs admises sont les suivantes :
- date_appel_telephonique : date au format AAAA-MM-JJ
- resultat_appel : ['usager joint', 'message vocal', 'téléphone inconnu']
- date_demande_creation_tiers : date au format AAAA-MM-JJ
- numero_titre_recette : numéro
- numero_tiers_GF : nombre
- date_creation_titre_recette : date au format AAAA-MM-JJ
- documents_a_payer : texte

In [11]:
# on identifie les lignes qui posent pb
# 
adh_bloc_ctx_lib_with_data_pb = adh_bloc_ctx_lib_with_data[
    ( 
        (~adh_bloc_ctx_lib_with_data['date_appel_telephonique'].astype(str).str.match("\d{4}-\d{2}-\d{2}"))
      & (adh_bloc_ctx_lib_with_data['date_appel_telephonique'].notna()) 
    )
    
      | (  
        (~adh_bloc_ctx_lib_with_data['resultat_appel'].isin(['usager joint', 'message vocal', 'téléphone inconnu']))
      & (adh_bloc_ctx_lib_with_data['resultat_appel'].notna()) 
    )
    
  | (  
        (~adh_bloc_ctx_lib_with_data['numero_titre_recette'].astype(str).str.match("\d"))
      & (adh_bloc_ctx_lib_with_data['numero_titre_recette'].notna()) 
    )
    
  | (  
        (~adh_bloc_ctx_lib_with_data['numero_tiers_GF'].astype(str).str.match("\d"))
      & (adh_bloc_ctx_lib_with_data['numero_tiers_GF'].notna()) 
    )  
    
  | (  
        (~adh_bloc_ctx_lib_with_data['date_demande_creation_tiers'].astype(str).str.match("\d{4}-\d{2}-\d{2}"))
      & (adh_bloc_ctx_lib_with_data['date_demande_creation_tiers'].notna()) 
    )
    
  | (  
        (~adh_bloc_ctx_lib_with_data['date_creation_titre_recette'].astype(str).str.match("\d{4}-\d{2}-\d{2}"))
      & (adh_bloc_ctx_lib_with_data['date_creation_titre_recette'].notna()) 
    )
]
len(adh_bloc_ctx_lib_with_data_pb)

0

On isole les lignes pour lesquelles il n'y a pas de contentieux.

In [12]:
adh_bloc_ctx_lib_with_data_without_ctx = adh_bloc_ctx_lib_with_data[adh_bloc_ctx_lib_with_data['contentieux'] == False]
len(adh_bloc_ctx_lib_with_data_without_ctx)

543

In [13]:
adh_bloc_ctx_lib_with_data_without_ctx[~adh_bloc_ctx_lib_with_data_without_ctx['date_appel_telephonique'].isna()]

,borrowernumber,cardnumber,userid,date_appel_telephonique,resultat_appel,date_demande_creation_tiers,numero_titre_recette,numero_tiers_GF,date_creation_titre_recette,documents_a_payer,dateofbirth,branchcode,categorycode,dateenrolled,dateexpiry,date_due,contentieux
22,297.0,X0001961898,X0001961898,2025-09-30,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,1974-12-17,MED,BIBL,2005-03-31,2025-11-21,NaN,False
96,1092.0,X0002580029,X0002580029,2025-09-19,usager joint,NaN,NaN,NaN,NaN,NaN,1971-02-13,MED,MEDC,2005-08-27,2025-10-08,NaN,False
140,1695.0,240570,240570,2025-09-30,usager joint,NaN,NaN,NaN,NaN,NaN,1970-05-24,MED,MEDP,2006-06-10,2026-07-03,NaN,False
150,1757.0,X0002832647,X0002832647,2025-10-22,usager joint,2021-07-15,NaN,41509,NaN,NaN,1971-10-05,MED,MEDC,2018-10-04,2026-08-07,NaN,False
171,1975.0,X0002492186,X0002492186,2025-09-30,usager joint,NaN,NaN,NaN,NaN,NaN,2003-04-24,MED,BIBL,2005-03-31,2026-05-25,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32037,87867.0,X0002856049,X0002856049,2025-04-03,message vocal,NaN,NaN,NaN,NaN,NaN,2020-03-22,MED,BIBL,2025-10-08,2026-10-08,NaN,False
32049,87879.0,X0002860046,X0002860046,2024-03-14,usager joint,2025-08-19,0,0,2025-08-19,C2500027173 - 10.95,2016-04-09,MED,BIBL,2025-10-08,2026-10-08,NaN,False
32050,87880.0,X0002860145,X0002860145,2024-03-14,usager joint,2025-08-19,0,0,2025-08-19,C2500027173 - 10.95,2017-09-29,MED,BIBL,2025-10-08,2026-10-08,NaN,False
32051,87881.0,X0002860152,X0002860152,2024-03-14,usager joint,2025-08-19,0,0,2025-08-19,C2500027173 - 10.95,2020-10-20,MED,BIBL,2025-10-08,2026-10-08,NaN,False
32310,88145.0,X0002859378,X0002859378,2023-04-27,téléphone inconnu,2024-08-21,5106248,201113,2024-08-29,C0005933471 - 11.60\r\nC2200004957 - 11.50\r\n...,2019-07-30,MED,BIBL,2025-10-21,2026-10-21,NaN,False

In [14]:
ctx2clean = adh_bloc_ctx_lib_with_data_without_ctx[~adh_bloc_ctx_lib_with_data_without_ctx['date_appel_telephonique'].isna()]
userid2clean = ctx2clean['userid'].tolist()

In [17]:
data = {"B_address": None,
        "B_address2": None,
        "contactnote": None}
#        "B_city": None,
#        "B_state": None,
#        "B_zipcode": None,
#        "B_country": None,
        
for userid in userid2clean[:500]:
    mod_borrower(userid, data)

data={"B_address": null, "B_address2": null, "contactnote": null}
X0001961898 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002580029 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
240570 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002832647 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002492186 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002349756 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
dyahiaoui : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002550497 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
Melan : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
ccarre : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002508498 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002145891 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002810096 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002499550 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002812007 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002348780 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0001489265 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002811246 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0001829279 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002825175 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002061177 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X160401 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002704715 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002230665 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002710693 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002203157 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002485065 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002400365 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0001809130 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002377766 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002550572 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
fouali : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002441894 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002493381 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002161129 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
bcapus : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002822051 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002489087 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002835068 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002543499 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002515380 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002496771 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002644066 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002351353 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002379272 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002491691 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002248950 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002412894 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002018690 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002550411 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002591049 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0001863468 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002039824 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002845470 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002636344 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002513294 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002210339 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002546353 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
soniaz : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}

X0002782836 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002431109 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002501727 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002832197 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002550527 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002852935 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002115825 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002125206 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002575759 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002844091 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002252452 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002779102 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002156620 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002568836 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002181455 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002755465 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002243283 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002207773 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002818290 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002779423 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002735580 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002485256 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002506289 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002225357 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002224589 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002353883 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002781020 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002381664 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002653501 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002392226 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002398112 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002431581 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002859415 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002784748 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002778761 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002260686 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002327044 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002327129 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
imane95 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002836515 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002275949 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002514819 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002686080 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002643540 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002423616 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002812588 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002309866 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002312088 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002804729 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002361697 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002425603 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002814377 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002427140 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002430713 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002432830 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002792460 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
GEPA : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002435251 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002164069 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002319162 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}

X0002435961 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002435978 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002438153 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002440064 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002440293 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002443225 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002443324 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002513409 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002806174 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002492315 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002706597 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002472072 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002476445 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002476735 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002476759 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002486482 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002487427 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002487434 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002487748 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002288727 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002499383 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002499499 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002499574 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002501574 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002504438 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002531625 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002287997 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002534794 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002535296 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002288048 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002812885 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002544755 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002477633 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002546407 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002546988 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002477749 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002547749 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002550589 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002608167 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002551876 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002553139 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002782317 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002509228 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002509235 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
mmeunier : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002513102 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002515724 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002515144 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002516943 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002518275 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002767703 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002523699 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002525525 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002525532 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002653006 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002530369 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002559889 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002858135 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002856704 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002691978 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}

X0002562704 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002566726 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002724980 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002715247 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002777719 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002570556 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002572154 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002838151 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002763590 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002573793 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002576299 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002576329 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002792835 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002836539 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002580890 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002750330 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002819761 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002856810 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002797175 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002700267 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002289458 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002589596 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002589602 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002289885 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002594804 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002736556 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002595610 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002595139 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002595627 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002595634 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002815596 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002703015 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002599557 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002601175 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002602998 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002603131 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002604213 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002638171 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002645483 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002646701 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002651095 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002653228 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002608327 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002742946 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002740850 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002748771 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002748436 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002748429 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002743899 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002359441 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002745916 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002754734 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002753270 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002753263 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002752730 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002758534 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002757421 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002758305 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002756240 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}

X0002744018 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002681146 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002760254 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002812953 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002773773 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002775234 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002764269 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002764467 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002761787 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002761794 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002731865 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002732497 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002731896 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002743646 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002728667 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002728520 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002734286 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002683010 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002762142 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002847566 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002705835 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002704951 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002805979 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002858609 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002702797 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002701455 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002701578 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002701004 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002767307 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002769691 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002373775 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002766744 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002766188 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002696157 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002699509 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002825052 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002713243 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002810782 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002695273 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002720340 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002694054 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002713823 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002769165 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002690827 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002716077 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002716381 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002716657 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002716770 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002717760 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002611822 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002725093 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002721392 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002721446 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002687667 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002686981 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002822570 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002690193 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002678399 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002677613 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002837178 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}

x0002817668 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002685205 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002684109 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002681719 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002613239 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002680927 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002680583 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002805214 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002804576 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002804262 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002803425 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002801902 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002801063 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002810195 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002800653 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002800691 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002807171 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002807096 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002806099 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002612713 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002794358 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002840451 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002841007 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002822983 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002857060 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002822655 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002799056 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002799285 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002797168 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002799414 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002796710 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002789743 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002789446 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002786193 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002785943 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002785936 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002785929 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002819969 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002819167 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002816890 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
x0002818573 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002814292 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002814131 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002815961 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002812724 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002811857 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002811109 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002815893 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002810423 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002810416 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002584416 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002643199 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002643212 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002775661 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002555232 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002778549 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002791890 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002778693 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002779348 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002780115 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}

X0002780085 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002778204 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002846002 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002851976 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002851303 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002851457 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002850733 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002851174 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002830650 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002831084 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002830841 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002831787 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002831985 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002832654 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002478289 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002832982 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002832098 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002785196 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002845708 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002781167 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002781211 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002846262 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002856100 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002856049 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002860046 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002860145 : b'{\n   "success" : true,\n   "modified_fields" : {}\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002860152 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'
data={"B_address": null, "B_address2": null, "contactnote": null}
X0002859378 : b'{\n   "modified_fields" : {},\n   "success" : true\n}\n'

On isole les lignes pour lesquelles il y a contentieux.

In [15]:
adh_bloc_ctx_lib_with_data_with_ctx = adh_bloc_ctx_lib_with_data[adh_bloc_ctx_lib_with_data['contentieux'] == True]
len(adh_bloc_ctx_lib_with_data_with_ctx)

2284

In [37]:
adh_bloc_ctx_lib_with_data_with_ctx['date_due_'] = pd.to_datetime(adh_bloc_ctx_lib_with_data_with_ctx['date_due'])
adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique_'] = pd.to_datetime(adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique'])

In [43]:
adh_bloc_ctx_lib_with_data_with_ctx.loc[
    adh_bloc_ctx_lib_with_data_with_ctx['date_due_'] > adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique_'],
    'ctx_statut'
] = 'nouveau'
adh_bloc_ctx_lib_with_data_with_ctx['newctx_appel'] = (adh_bloc_ctx_lib_with_data_with_ctx['date_due_'] - adh_bloc_ctx_lib_with_data_with_ctx['date_appel_telephonique_']).dt.days

In [39]:
adh_bloc_ctx_lib_with_data_with_ctx['ctx_statut'].value_counts()

nouveau    351
Name: ctx_statut, dtype: int64

In [45]:
new_ctx = adh_bloc_ctx_lib_with_data_with_ctx[adh_bloc_ctx_lib_with_data_with_ctx['ctx_statut'] == 'nouveau']
new_ctx

,borrowernumber,cardnumber,userid,date_appel_telephonique,resultat_appel,date_demande_creation_tiers,numero_titre_recette,numero_tiers_GF,date_creation_titre_recette,documents_a_payer,...,branchcode,categorycode,dateenrolled,dateexpiry,date_due,contentieux,date_due_,date_appel_telephonique_,ctx_statut,newctx_appel
176,2030.0,X0002587394,X0002587394,2021-10-22,usager joint,2025-08-19,NaN,201254,NaN,C1400006532 - 9.90\r\nC1400009101 - 22.00,...,MED,BIBL,2022-10-25,2025-01-05,2024-02-16,True,2024-02-16,2021-10-22,nouveau,847.0
213,2418.0,X0002349756,X0002349756,2023-07-15,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,...,MED,MEDC,2007-02-28,2026-05-06,2025-07-15,True,2025-07-15,2023-07-15,nouveau,731.0
227,2577.0,X0002039459,X0002039459,2023-09-19,message vocal,NaN,NaN,NaN,NaN,NaN,...,BUS,BIBL,2008-08-28,2026-02-05,2025-05-31,True,2025-05-31,2023-09-19,nouveau,620.0
268,2973.0,X0002716022,X0002716022,2022-11-05,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2010-07-24,2025-02-21,2024-05-16,True,2024-05-16,2022-11-05,nouveau,558.0
271,3020.0,X0002550497,X0002550497,2024-09-19,message vocal,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2006-08-09,2026-01-19,2025-07-12,True,2025-07-12,2024-09-19,nouveau,296.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29080,84858.0,X0002818702,X0002818702,2025-06-13,usager joint,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-03-23,2026-03-23,2025-07-09,True,2025-07-09,2025-06-13,nouveau,26.0
29404,85183.0,X0002814919,X0002814919,2023-02-03,message vocal,2023-09-20,20230138,100168,2023-09-21,C2400002345 - 33.00,...,MED,BIBL,2025-04-11,2026-04-11,2025-06-10,True,2025-06-10,2023-02-03,nouveau,858.0
29430,85209.0,X0002814520,X0002814520,2025-02-06,message vocal,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-04-15,2026-04-15,2025-05-06,True,2025-05-06,2025-02-06,nouveau,89.0
30525,86318.0,X0002851853,X0002851853,2021-05-15,message vocal,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-06-25,2026-06-25,2025-07-16,True,2025-07-16,2021-05-15,nouveau,1523.0
30588,86382.0,X0002851457,X0002851457,2021-05-19,téléphone inconnu,NaN,NaN,NaN,NaN,NaN,...,MED,BIBL,2025-06-29,2026-06-29,2025-07-20,True,2025-07-20,2021-05-19,nouveau,1523.0

In [47]:
new_ctx[new_ctx['newctx_appel'] < 90].to_excel("test_ctx.xlsx")